apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dns-management-service.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "dns-management-service.labels" . | indent 4 }}
    app.kubernetes.io/component: configuration
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
