apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dns-management-service.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "dns-management-service.labels" . | indent 4 }}
    app.kubernetes.io/component: configuration
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  OTEL_SERVICE_NAME: {{ .Values.otel.serviceName | quote }}
  OTEL_EXPORT_MODE: {{ .Values.otel.mode | quote }}
  OTEL_EXPORT_ENDPOINT: {{ .Values.otel.endpoint | quote }}
  OTEL_EXPORT_TIMEOUT_MS: {{ .Values.otel.exportTimeoutMs | quote }}
  DEBUG_MODE: {{ ternary "true" "false" .Values.debug.enabled | quote }}
