apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-management-service.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "dns-management-service.labels" . | indent 4 }}
    app.kubernetes.io/component: service
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "dns-management-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
