apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../crd
  - rbac.yaml
  - deployment.yaml
  - test-operator-configmap.yaml
  - test-operator-rbac.yaml
  - test-operator-deployment.yaml
