apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - collector-deployment.yaml
  - collector-service.yaml
  - clickhouse-statefulset.yaml
  - clickhouse-service.yaml
  - grafana-dashboard-provider.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: otel-collector-config
    files:
      - collector.yaml=../../monitoring/otel/collector-clickhouse.yaml
  - name: grafana-clickhouse-datasource
    files:
      - clickhouse.yaml=../../monitoring/grafana/provisioning/datasources/clickhouse.yaml
  - name: grafana-dns-observability-dashboard
    files:
      - dns-observability-v1.json=../../monitoring/grafana/dashboards/dns-observability-v1.json
